### PR TITLE
Feature/createtrip

### PR DESCRIPTION
**Pull request by RSibaja88**
John and Fati, if you guys could look this PR over. It contains the login, home and create a trip pages.

### CODE REVIEW

**Review by munal92 — COMMENTED** [review]
Looks good to me

**Review by jgreenweb — COMMENTED** [review]
Looks good to me, maybe put create trip under secure routes

**Review by jgreenweb — DISMISSED** [review]
Test approve

**Review by jgreenweb — APPROVED** [review]
Seems good to me

**Pull request merged**
